name: Build Packages

on:
  workflow_call:
    inputs:
      upload_to_release:
        type: boolean
        default: false
        required: false
      use_production_signing:
        type: boolean
        default: false
        required: false
      macos_runner:
        type: string
        default: macos-latest
        required: false
      windows_runner:
        type: string
        default: windows-latest
        required: false
      linux_runner:
        type: string
        default: ubuntu-latest
        required: false

jobs:
  build-macos:
    runs-on: ${{ inputs.macos_runner }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Universal Python
      run: |
        # Download and install the Python 3.12.2 universal2 installer
        curl -O https://www.python.org/ftp/python/3.12.2/python-3.12.2-macos11.pkg
        sudo installer -pkg python-3.12.2-macos11.pkg -target /
    
    - name: Update PATH for Python 3.12.2
      run: echo "/Library/Frameworks/Python.framework/Versions/3.12/bin" >> $GITHUB_PATH
    
    - name: Verify Python Version
      run: python3 --version

    - name: Create Virtual Environment and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        # Pin setuptools to a version compatible with py2app to avoid the copying error
        pip install --upgrade pip setuptools==66.1.1 wheel
        pip install py2app PyQt5

    - name: Build Universal App
      run: |
        source venv/bin/activate
        rm -rf build/ dist/
        python setup.py py2app
        
    - name: Verify Universal Binary
      run: |
        # Check that the library includes both arm64 and x86_64 slices.
        lipo -info dist/P2PP.app/Contents/Resources/lib/python3.12/PyQt5/QtWebEngineWidgets.abi3.so
        
    - name: Sign Application (Development)
      if: ${{ !inputs.use_production_signing }}
      run: |
        # Ad-hoc signing for development
        codesign --force --deep --sign - "dist/P2PP.app"
        
    - name: Sign Application (Production)
      if: ${{ inputs.use_production_signing }}
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Import certificate from secrets
        echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
        
        # Create keychain and import certificate
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        
        # Sign the application
        codesign --force --deep --sign "Developer ID Application: $APPLE_TEAM_ID" \
                --options runtime \
                --entitlements "entitlements.plist" \
                "dist/P2PP.app"
        
        # Verify signature
        codesign --verify --deep --strict "dist/P2PP.app"
        
    - name: Create DMG
      run: |
        create-dmg \
          --volname "P2PP" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "P2PP.app" 175 120 \
          --hide-extension "P2PP.app" \
          --app-drop-link 425 120 \
          "dist/P2PP.dmg" \
          "dist/P2PP.app"
          
    - name: Sign DMG (Production)
      if: ${{ inputs.use_production_signing }}
      run: |
        codesign --force --sign "Developer ID Application: $APPLE_TEAM_ID" \
                --options runtime \
                "dist/P2PP.dmg"

    - name: Upload to Release
      if: inputs.upload_to_release && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/P2PP.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      if: ${{ !inputs.upload_to_release }}
      uses: actions/upload-artifact@v4
      with:
        name: p2pp-macos
        path: dist/

  build-windows:
    runs-on: ${{ inputs.windows_runner }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-win.txt
        
    - name: Build Windows Package
      run: |
        python setup.py bdist_msi

    - name: Create Self-Signed Certificate (Development)
      if: ${{ !inputs.use_production_signing }}
      run: |
        # Create a self-signed certificate for development
        New-SelfSignedCertificate -Type Custom -Subject "CN=P2PP Development" -KeyUsage DigitalSignature `
          -FriendlyName "P2PP Development Certificate" -CertStoreLocation "Cert:\CurrentUser\My" `
          -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}false")
        
        # Export certificate info for signing
        $cert = Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object {$_.FriendlyName -eq "P2PP Development Certificate"}
        echo "SIGNING_CERT_THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Sign MSI (Development)
      if: ${{ !inputs.use_production_signing }}
      run: |
        # Sign with self-signed certificate
        $cert = Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object {$_.Thumbprint -eq $env:SIGNING_CERT_THUMBPRINT}
        Set-AuthenticodeSignature -FilePath "dist\*.msi" -Certificate $cert -TimestampServer "http://timestamp.digicert.com"
      shell: pwsh

    - name: Sign MSI (Production)
      if: ${{ inputs.use_production_signing }}
      env:
        WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
        WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
      run: |
        # Decode and save the certificate
        $certBytes = [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE)
        $certPath = "certificate.pfx"
        [IO.File]::WriteAllBytes($certPath, $certBytes)
        
        # Sign the MSI
        signtool sign /f $certPath /p $env:WINDOWS_CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 "dist\*.msi"
        
        # Clean up
        Remove-Item $certPath
      shell: pwsh

    - name: Upload to Release
      if: inputs.upload_to_release && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      if: ${{ !inputs.upload_to_release }}
      uses: actions/upload-artifact@v4
      with:
        name: p2pp-windows
        path: dist/

  build-linux:
    runs-on: ${{ inputs.linux_runner }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm build-essential debhelper python3-all dh-python python3-setuptools python3-pip python3-stdeb
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linux.txt
        
    - name: Build Linux Packages
      run: |
        # Build RPM
        python setup.py bdist_rpm
        
        # Build DEB
        python setup.py sdist
        cd dist
        mkdir build_deb
        tar xvf p2pp-*.tar.gz -C build_deb --strip-components=1
        cd build_deb
        
        mkdir -p debian/source
        cp ../../debian/control debian/
        cp ../../debian/changelog debian/
        cp ../../debian/rules debian/
        echo "3.0 (native)" > debian/source/format
        
        chmod +x debian/rules
        if [ -f "scripts/post_install.sh" ]; then
          chmod +x scripts/post_install.sh
        fi
        if [ -f "scripts/post_uninstall.sh" ]; then
          chmod +x scripts/post_uninstall.sh
        fi
        
        dpkg-buildpackage -us -uc
        cd ..
        mkdir -p deb
        cp *.deb deb/

    - name: Upload to Release
      if: inputs.upload_to_release && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.rpm
          dist/deb/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      if: ${{ !inputs.upload_to_release }}
      uses: actions/upload-artifact@v4
      with:
        name: p2pp-linux
        path: dist/ 