name: Build Multi-Platform Binaries

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']  # Specify a stable version

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          source venv/Scripts/activate
        else
          source venv/bin/activate
        fi
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          pip install py2app
        else
          pip install cx_Freeze
        fi
      shell: bash

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          python setup.py py2app
        else
          python setup.py build
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: p2pp-${{ matrix.os }}
        path: |
          dist/
          build/