name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/build-packages.yml
    with:
      upload_to_release: true
      use_production_signing: false # ${{ secrets.APPLE_CERTIFICATE != '' && secrets.WINDOWS_CERTIFICATE != '' }}

  update-release-notes:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Update Release Description
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ### macOS Downloads
            - For Apple Silicon Macs (M1/M2): Download `P2PP-arm64.dmg`
            - For Intel Macs: Download `P2PP-x64.dmg`
            
            ### Other Platforms
            - Windows: Download the `.msi` installer
            - Linux: Download either `.deb` or `.rpm` based on your distribution